#ifndef __INC_METIN2_ITEM_LENGTH_H__
#define __INC_METIN2_ITEM_LENGTH_H__

enum EItemProtoColumns {
	COL_VNUM,
	COL_NAME,
	COL_TYPE,
	COL_SUBTYPE,
	COL_MASKED_TYPE,
	COL_MASKED_SUBTYPE,
	COL_SIZE,
	COL_ANTIFLAG,
	COL_FLAG,
	COL_WEARFLAG,
	COL_IMMUNEFLAG,
	COL_BUY_PRICE,
	COL_SELL_PRICE,
	COL_REFINED_VNUM,
	COL_REFINE_SET,
	COL_67MATERIAL,
	COL_MAGIC_PCT,
	COL_LIMIT_TYPE_0,
	COL_LIMIT_VALUE_0,
	COL_LIMIT_TYPE_1,
	COL_LIMIT_VALUE_1,
	COL_APPLY_TYPE_0,
	COL_APPLY_VALUE_0,
	COL_APPLY_TYPE_1,
	COL_APPLY_VALUE_1,
	COL_APPLY_TYPE_2,
	COL_APPLY_VALUE_2,
	COL_APPLY_TYPE_3,
	COL_APPLY_VALUE_3,
	COL_VALUE0,
	COL_VALUE1,
	COL_VALUE2,
	COL_VALUE3,
	COL_VALUE4,
	COL_VALUE5,
	COL_SPECULAR,
	COL_SOCKET_PCT,
	COL_ADDON_TYPE,

	COL_MAX_NUM,
};

enum EItemMisc
{
	ITEM_NAME_MAX_LEN			= 32,
	ITEM_VALUES_MAX_NUM			= 6,
	ITEM_SMALL_DESCR_MAX_LEN	= 256,
	ITEM_LIMIT_MAX_NUM			= 2,
	ITEM_APPLY_MAX_NUM			= 4,
	ITEM_SOCKET_MAX_NUM			= 3,
	ITEM_MAX_COUNT				= 200,
	ITEM_ATTRIBUTE_MAX_NUM		= 7,
	ITEM_ATTRIBUTE_MAX_LEVEL	= 5,
	ITEM_AWARD_WHY_MAX_LEN		= 50,

	REFINE_MATERIAL_MAX_NUM		= 5,

	ITEM_ELK_VNUM				= 50026,
};

const BYTE ITEM_SOCKET_REMAIN_SEC = 0;
enum EItemValueIdice
{
	ITEM_VALUE_DRAGON_SOUL_POLL_OUT_BONUS_IDX = 0,
	ITEM_VALUE_CHARGING_AMOUNT_IDX = 0,
	ITEM_VALUE_SECONDARY_COIN_UNIT_IDX = 0,
};
enum EItemDragonSoulSockets
{
	ITEM_SOCKET_DRAGON_SOUL_ACTIVE_IDX = 2,
	ITEM_SOCKET_CHARGING_AMOUNT_IDX = 2,
};
// 헐 이거 미친거 아니야?
// 나중에 소켓 확장하면 어쩌려고 이지랄 -_-;;;
enum EItemUniqueSockets
{
	ITEM_SOCKET_UNIQUE_SAVE_TIME = ITEM_SOCKET_MAX_NUM - 2,
	ITEM_SOCKET_UNIQUE_REMAIN_TIME = ITEM_SOCKET_MAX_NUM - 1
};

enum EItemTypes
{
    ITEM_NONE,              //0
    ITEM_WEAPON,            //1//무기
    ITEM_ARMOR,             //2//갑옷
    ITEM_USE,               //3//아이템 사용
    ITEM_AUTOUSE,           //4
    ITEM_MATERIAL,          //5
    ITEM_SPECIAL,           //6 //스페셜 아이템
    ITEM_TOOL,              //7
    ITEM_LOTTERY,           //8//복권
    ITEM_ELK,               //9//돈
    ITEM_METIN,             //10
    ITEM_CONTAINER,         //11
    ITEM_FISH,              //12//낚시
    ITEM_ROD,               //13
    ITEM_RESOURCE,          //14
    ITEM_CAMPFIRE,          //15
    ITEM_UNIQUE,            //16
    ITEM_SKILLBOOK,         //17
    ITEM_QUEST,             //18
    ITEM_POLYMORPH,         //19
    ITEM_TREASURE_BOX,      //20//보물상자
    ITEM_TREASURE_KEY,      //21//보물상자 열쇠
    ITEM_SKILLFORGET,       //22
    ITEM_GIFTBOX,           //23
    ITEM_PICK,              //24
    ITEM_HAIR,              //25//머리
    ITEM_TOTEM,             //26//토템
	ITEM_BLEND,				//27//생성될때 랜덤하게 속성이 붙는 약물
	ITEM_COSTUME,			//28//코스츔 아이템 (2011년 8월 추가된 코스츔 시스템용 아이템)
	ITEM_DS,				//29 //용혼석
	ITEM_SPECIAL_DS,		//30 // 특수한 용혼석 (DS_SLOT에 착용하는 UNIQUE 아이템이라 생각하면 됨)
	ITEM_EXTRACT,			//31 추출도구.
	ITEM_SECONDARY_COIN,	//32 ?? 명도전??
	ITEM_RING,				//33 반지
	ITEM_BELT,				//34 벨트
	ITEM_PET,				//35
	ITEM_MEDIUM,			//36
	ITEM_GACHA,				//37
	ITEM_SOUL,				//38
};

enum EMetinSubTypes
{
	METIN_NORMAL,
	METIN_GOLD,
};

enum EWeaponSubTypes
{
	WEAPON_SWORD,
	WEAPON_DAGGER,
	WEAPON_BOW,
	WEAPON_TWO_HANDED,
	WEAPON_BELL,
	WEAPON_FAN,				// 5
	WEAPON_ARROW,
	WEAPON_MOUNT_SPEAR,
	WEAPON_CLAW,
	WEAPON_QUIVER,
	WEAPON_BOUQUET,			// 10
	
	WEAPON_NUM_TYPES,
};

enum EArmorSubTypes
{
	ARMOR_BODY,
	ARMOR_HEAD,
	ARMOR_SHIELD,
	ARMOR_WRIST,
	ARMOR_FOOTS,
	ARMOR_NECK,
	ARMOR_EAR,
	ARMOR_PENDANT,
	ARMOR_NUM_TYPES
};

enum ECostumeSubTypes
{
	COSTUME_BODY = ARMOR_BODY,			// [중요!!] ECostumeSubTypes enum value는  종류별로 EArmorSubTypes의 그것과 같아야 함.
	COSTUME_HAIR = ARMOR_HEAD,			// 이는 코스츔 아이템에 추가 속성을 붙이겠다는 사업부의 요청에 따라서 기존 로직을 활용하기 위함임.
	COSTUME_MOUNT,
	COSTUME_ACCE,
	COSTUME_WEAPON,
	COSTUME_AURA,
	COSTUME_NUM_TYPES,
};

enum EDragonSoulSubType
{
	DS_SLOT1,
	DS_SLOT2,
	DS_SLOT3,
	DS_SLOT4,
	DS_SLOT5,
	DS_SLOT6,
	DS_SLOT_MAX,
};

enum EDragonSoulGradeTypes
{
	DRAGON_SOUL_GRADE_NORMAL,
	DRAGON_SOUL_GRADE_BRILLIANT,
	DRAGON_SOUL_GRADE_RARE,
	DRAGON_SOUL_GRADE_ANCIENT,
	DRAGON_SOUL_GRADE_LEGENDARY,
	DRAGON_SOUL_GRADE_MAX,

};

enum EDragonSoulStepTypes
{
	DRAGON_SOUL_STEP_LOWEST,
	DRAGON_SOUL_STEP_LOW,
	DRAGON_SOUL_STEP_MID,
	DRAGON_SOUL_STEP_HIGH,
	DRAGON_SOUL_STEP_HIGHEST,
	DRAGON_SOUL_STEP_MAX,
};
#define DRAGON_SOUL_STRENGTH_MAX 7

enum EDSInventoryMaxNum
{
	DRAGON_SOUL_INVENTORY_MAX_NUM = DS_SLOT_MAX * DRAGON_SOUL_GRADE_MAX * DRAGON_SOUL_BOX_SIZE,
};

enum EFishSubTypes
{
	FISH_ALIVE,
	FISH_DEAD,
};

enum EResourceSubTypes
{
	RESOURCE_FISHBONE,			// 0
	RESOURCE_WATERSTONEPIECE,	// 1
	RESOURCE_WATERSTONE,		// 2
	RESOURCE_BLOOD_PEARL,		// 3
	RESOURCE_BLUE_PEARL,		// 4
	RESOURCE_WHITE_PEARL,		// 5
	RESOURCE_BUCKET,			// 6
	RESOURCE_CRYSTAL,			// 7
	RESOURCE_GEM,				// 8
	RESOURCE_STONE,				// 9
	RESOURCE_METIN,				// 10
	RESOURCE_ORE,				// 11
	RESOURCE_AURA,				// 12
};

enum EUniqueSubTypes
{
	UNIQUE_NONE,
	UNIQUE_BOOK,
	UNIQUE_SPECIAL_RIDE,
	UNIQUE_SPECIAL_MOUNT_RIDE,
};

enum EUseSubTypes
{
	USE_POTION,					// 0
	USE_TALISMAN,
	USE_TUNING,
	USE_MOVE,
	USE_TREASURE_BOX,
	USE_MONEYBAG,
	USE_BAIT,
	USE_ABILITY_UP,
	USE_AFFECT,
	USE_CREATE_STONE,
	USE_SPECIAL,				// 10
	USE_POTION_NODELAY,
	USE_CLEAR,
	USE_INVISIBILITY,
	USE_DETACHMENT,
	USE_BUCKET,
	USE_POTION_CONTINUE,
	USE_CLEAN_SOCKET,
	USE_CHANGE_ATTRIBUTE,
	USE_ADD_ATTRIBUTE,
	USE_ADD_ACCESSORY_SOCKET,	// 20
	USE_PUT_INTO_ACCESSORY_SOCKET,
	USE_ADD_ATTRIBUTE2,
	USE_RECIPE,
	USE_CHANGE_ATTRIBUTE2,
	USE_BIND,
	USE_UNBIND,
	USE_TIME_CHARGE_PER,
	USE_TIME_CHARGE_FIX,				// 28
	USE_PUT_INTO_BELT_SOCKET,			// 29 벨트 소켓에 사용할 수 있는 아이템 
	USE_PUT_INTO_RING_SOCKET,			// 30 반지 소켓에 사용할 수 있는 아이템 (유니크 반지 말고, 새로 추가된 반지 슬롯)
	
	USE_CHANGE_COSTUME_ATTR,			// 31
	USE_RESET_COSTUME_ATTR,				// 32
	
	USE_SELECT_ATTRIBUTE = 34,			// 34
	USE_FLOWER,							// 35
	USE_EMOTION_PACK,					// 36
	
	USE_ELEMENT_UPGRADE,				// 37
	USE_ELEMENT_DOWNGRADE,				// 38
	USE_ELEMENT_CHANGE,					// 39
	
	USE_UNK40,						// 40
};

enum EExtractSubTypes
{
	EXTRACT_DRAGON_SOUL,
	EXTRACT_DRAGON_HEART,
};

enum EAutoUseSubTypes
{
	AUTOUSE_POTION,
	AUTOUSE_ABILITY_UP,
	AUTOUSE_BOMB,
	AUTOUSE_GOLD,
	AUTOUSE_MONEYBAG,
	AUTOUSE_TREASURE_BOX
};

enum EMaterialSubTypes
{
	MATERIAL_LEATHER,
	MATERIAL_BLOOD,
	MATERIAL_ROOT,
	MATERIAL_NEEDLE,
	MATERIAL_JEWEL,
	MATERIAL_DS_REFINE_NORMAL, 		// 5
	MATERIAL_DS_REFINE_BLESSED, 
	MATERIAL_DS_REFINE_HOLLY,
	MATERIAL_DS_CHANGE_ATTR,
};

enum ESpecialSubTypes
{
	SPECIAL_MAP,
	SPECIAL_KEY,
	SPECIAL_DOC,
	SPECIAL_SPIRIT,
};

enum EToolSubTypes
{
	TOOL_FISHING_ROD
};

enum ELotterySubTypes
{
	LOTTERY_TICKET,
	LOTTERY_INSTANT
};

enum EPetSubTypes
{
	PET_EGG,
	PET_UPBRINGING,
	PET_BAG,
	PET_FEEDSTUFF,
	PET_SKILL,
	PET_SKILL_DEL_BOOK,
	PET_NAME_CHANGE,
	PET_EXPFOOD,
	PET_SKILL_ALL_DEL_BOOK,
	PET_EXPFOOD_PER,
	PET_ATTR_DETERMINE,
	PET_ATTR_CHANGE,
	PET_PAY,
	PET_PRIMIUM_FEEDSTUFF,
};

enum EMediumSubTypes
{
	MEDIUM_MOVE_COSTUME_ATTR,
	MEDIUM_MOVE_ACCE_ATTR,
};

enum EGachaSubTypes
{
	USE_GACHA,
	GEM_LUCKY_BOX_GACHA,
	SPECIAL_LUCKY_BOX_GACHA,
};

enum ESoulSubTypes
{
	SOUL_RED,
	SOUL_BLUE,
};

enum EItemMaskTypes
{
	MASK_ITEM_NONE,
	MASK_ITEM_MOUNT_PET,
	MASK_ITEM_EQUIPMENT_WEAPON,
	MASK_ITEM_EQUIPMENT_ARMOR,
	MASK_ITEM_EQUIPMENT_JEWELRY,
	MASK_ITEM_TUNING,
	MASK_ITEM_POTION,
	MASK_ITEM_FISHING_PICK,
	MASK_ITEM_DRAGON_STONE,
	MASK_ITEM_COSTUMES,
	MASK_ITEM_SKILL,
	MASK_ITEM_UNIQUE,
	MASK_ITEM_ETC,
};

enum EMountPetMaskSubTypes
{
	MASK_MOUNT_PET_MOUNT,
	MASK_MOUNT_PET_CHARGED_PET,
	MASK_MOUNT_PET_FREE_PET,
	MASK_MOUNT_PET_EGG,
};

enum EWeaponMaskTypes
{
	MASK_EQUIPMENT_WEAPON_SWORD,
	MASK_EQUIPMENT_WEAPON_DAGGER,
	MASK_EQUIPMENT_WEAPON_BOW,
	MASK_EQUIPMENT_WEAPON_TWO_HANDED,
	MASK_EQUIPMENT_WEAPON_BELL,
	MASK_EQUIPMENT_WEAPON_CLAW,
	MASK_EQUIPMENT_WEAPON_FAN,
	MASK_EQUIPMENT_WEAPON_MOUNT_SPEAR,
	MASK_EQUIPMENT_WEAPON_ARROW,
};

enum EArmorMaskSubTypes
{
	MASK_EQUIPMENT_ARMOR_BODY,
	MASK_EQUIPMENT_ARMOR_HEAD,
	MASK_EQUIPMENT_ARMOR_SHIELD,
};

enum EJewelryMaskSubTypes
{
	MASK_EQUIPMENT_JEWELRY_ARMOR_WRIST,
	MASK_EQUIPMENT_JEWELRY_ARMOR_FOOTS,
	MASK_EQUIPMENT_JEWELRY_ARMOR_NECK,
	MASK_EQUIPMENT_JEWELRY_ARMOR_EAR,
	MASK_EQUIPMENT_JEWELRY_ITEM_BELT,
	MASK_EQUIPMENT_JEWELRY_ARMOR_PENDANT,
};

enum ETuningMaskSubTypes
{
	MASK_TUNING_RESOURCE,
	MASK_TUNING_STONE,
	MASK_TUNING_ETC,
};

enum EPotionMaskSubTypes
{
	MASK_POTION_ABILITY,
	MASK_POTION_HAIRDYE,
	MASK_POTION_ETC,
};

enum EFishMaskSubTypes
{
	MASK_FISHING_PICK_FISHING_POLE,
	MASK_FISHING_PICK_EQUIPMENT_PICK,
	MASK_FISHING_PICK_FOOD,
	MASK_FISHING_PICK_STONE,
	MASK_FISHING_PICK_ETC,
};

enum EDragonSoulMaskSubTypes
{
	MASK_DRAGON_STONE_DRAGON_DIAMOND,
	MASK_DRAGON_STONE_DRAGON_RUBY,
	MASK_DRAGON_STONE_DRAGON_JADE,
	MASK_DRAGON_STONE_DRAGON_SAPPHIRE,
	MASK_DRAGON_STONE_DRAGON_GARNET,
	MASK_DRAGON_STONE_DRAGON_ONYX,
	MASK_DRAGON_STONE_ETC,
};

enum ECostumeMaskSubTypes
{
	MASK_COSTUMES_COSTUME_WEAPON,
	MASK_COSTUMES_COSTUME_BODY,
	MASK_COSTUMES_COSTUME_HAIR,
	MASK_COSTUMES_SASH,
	MASK_COSTUMES_AURA,
	MASK_COSTUMES_ETC,
};

enum ESkillbookMaskSubTypes
{
	MASK_SKILL_PAHAE,
	MASK_SKILL_SKILL_BOOK,
	MASK_SKILL_BOOK_OF_OBLIVION,
	MASK_SKILL_ETC,
};

enum EUniqueMaskSubTypes
{
	MASK_UNIQUE_ABILITY,
	MASK_UNIQUE_ETC,
};

enum EETcMaskSubTypes
{
	MASK_ETC_GIFTBOX,
	MASK_ETC_MATRIMORY,
	MASK_ETC_EVENT,
	MASK_ETC_SEAL,
	MASK_ETC_PARTI,
	MASK_ETC_POLYMORPH,
	MASK_ETC_RECIPE,
	MASK_ETC_ETC,
};

enum EItemFlag
{
	ITEM_FLAG_REFINEABLE		= (1 << 0),
	ITEM_FLAG_SAVE			= (1 << 1),
	ITEM_FLAG_STACKABLE		= (1 << 2),	// 여러개 합칠 수 있음
	ITEM_FLAG_COUNT_PER_1GOLD	= (1 << 3),
	ITEM_FLAG_SLOW_QUERY		= (1 << 4),
	ITEM_FLAG_UNUSED01		= (1 << 5),	// UNUSED
	ITEM_FLAG_UNIQUE		= (1 << 6),
	ITEM_FLAG_MAKECOUNT		= (1 << 7),
	ITEM_FLAG_IRREMOVABLE		= (1 << 8),
	ITEM_FLAG_CONFIRM_WHEN_USE	= (1 << 9),
	ITEM_FLAG_QUEST_USE		= (1 << 10),
	ITEM_FLAG_QUEST_USE_MULTIPLE	= (1 << 11),
	ITEM_FLAG_QUEST_GIVE		= (1 << 12),
	ITEM_FLAG_LOG			= (1 << 13),
	ITEM_FLAG_APPLICABLE		= (1 << 14),
};

enum EItemAntiFlag
{
	ITEM_ANTIFLAG_FEMALE	= (1 << 0), // 여성 사용 불가
	ITEM_ANTIFLAG_MALE		= (1 << 1), // 남성 사용 불가
	ITEM_ANTIFLAG_WARRIOR	= (1 << 2), // 무사 사용 불가
	ITEM_ANTIFLAG_ASSASSIN	= (1 << 3), // 자객 사용 불가
	ITEM_ANTIFLAG_SURA		= (1 << 4), // 수라 사용 불가 
	ITEM_ANTIFLAG_SHAMAN	= (1 << 5), // 무당 사용 불가
	ITEM_ANTIFLAG_GET		= (1 << 6), // 집을 수 없음
	ITEM_ANTIFLAG_DROP		= (1 << 7), // 버릴 수 없음
	ITEM_ANTIFLAG_SELL		= (1 << 8), // 팔 수 없음
	ITEM_ANTIFLAG_EMPIRE_A	= (1 << 9), // A 제국 사용 불가
	ITEM_ANTIFLAG_EMPIRE_B	= (1 << 10), // B 제국 사용 불가
	ITEM_ANTIFLAG_EMPIRE_C	= (1 << 11), // C 제국 사용 불가
	ITEM_ANTIFLAG_SAVE		= (1 << 12), // 저장되지 않음
	ITEM_ANTIFLAG_GIVE		= (1 << 13), // 거래 불가
	ITEM_ANTIFLAG_PKDROP	= (1 << 14), // PK시 떨어지지 않음
	ITEM_ANTIFLAG_STACK		= (1 << 15), // 합칠 수 없음
	ITEM_ANTIFLAG_MYSHOP	= (1 << 16), // 개인 상점에 올릴 수 없음
	ITEM_ANTIFLAG_SAFEBOX	= (1 << 17), // 창고에 넣을 수 없음
	ITEM_ANTIFLAG_WOLFMAN	= (1 << 18),
	ITEM_ANTIFLAG_PET		= (1 << 19),
	ITEM_ANTIFLAG_QUICKSLOT = (1 << 20),
	ITEM_ANTIFLAG_CHANGELOOK = (1 << 21),
	ITEM_ANTIFLAG_REINFORCE = (1 << 22),
	ITEM_ANTIFLAG_ENCHANT	= (1 << 23),
	ITEM_ANTIFLAG_PETFEED	= (1 << 24),
	ITEM_ANTIFLAG_ENERGY	= (1 << 25),
	ITEM_ANTIFLAG_APPLY		= (1 << 26),
	ITEM_ANTIFLAG_ACCE		= (1 << 27),
	ITEM_ANTIFLAG_MAIL		= (1 << 28),
};

enum EItemWearableFlag
{
	WEARABLE_BODY	= (1 << 0),
	WEARABLE_HEAD	= (1 << 1),
	WEARABLE_FOOTS	= (1 << 2),
	WEARABLE_WRIST	= (1 << 3),
	WEARABLE_WEAPON	= (1 << 4),
	WEARABLE_NECK	= (1 << 5),
	WEARABLE_EAR	= (1 << 6),
	WEARABLE_UNIQUE	= (1 << 7),
	WEARABLE_SHIELD	= (1 << 8),
	WEARABLE_ARROW	= (1 << 9),
	WEARABLE_HAIR	= (1 << 10),
	WEARABLE_ABILITY	= (1 << 11),
	WEARABLE_PENDANT	= (1 << 12),
};

enum ELimitTypes
{
	LIMIT_NONE,

	LIMIT_LEVEL,
	LIMIT_STR,
	LIMIT_DEX,
	LIMIT_INT,
	LIMIT_CON,
	LIMIT_PCBANG,

	/// 착용 여부와 상관 없이 실시간으로 시간 차감 (socket0에 소멸 시간이 박힘: unix_timestamp 타입)
	LIMIT_REAL_TIME,						

	/// 아이템을 맨 처음 사용(혹은 착용) 한 순간부터 리얼타임 타이머 시작 
	/// 최초 사용 전에는 socket0에 사용가능시간(초단위, 0이면 프로토의 limit value값 사용) 값이 쓰여있다가 
	/// 아이템 사용시 socket1에 사용 횟수가 박히고 socket0에 unix_timestamp 타입의 소멸시간이 박힘.
	LIMIT_REAL_TIME_START_FIRST_USE,

	/// 아이템을 착용 중일 때만 사용 시간이 차감되는 아이템
	/// socket0에 남은 시간이 초단위로 박힘. (아이템 최초 사용시 해당 값이 0이면 프로토의 limit value값을 socket0에 복사)
	LIMIT_TIMER_BASED_ON_WEAR,

	LIMIT_MAX_NUM
};

enum EAttrAddonTypes
{
	ATTR_ADDON_NONE,
	// positive values are reserved for set
	ATTR_DAMAGE_ADDON = -1,
};

enum ERefineType
{
	REFINE_TYPE_NORMAL,
	REFINE_TYPE_NOT_USED1,
	REFINE_TYPE_SCROLL,
	REFINE_TYPE_HYUNIRON,
	REFINE_TYPE_MONEY_ONLY,
	REFINE_TYPE_MUSIN,
	REFINE_TYPE_BDRAGON,
};

#endif
